sudo: required

env:
- CONSUMER_KEY=consumerKey CONSUMER_SECRET=consumerSecret CALLBACK_URL=http://localhost:8080/oauth/twitter/callback PORT=8080 HOMEPAGE=/ HOST=localhost:8080 PROTOCOL=http

services:
- docker

script:
- docker build --file Dockerfile.test --tag tweeters-stats-golang-test .
- docker run -it --rm --env NEW_RELIC_LICENSE_KEY= tweeters-stats-golang-test