sudo: required
language: node_js
node_js:
- "8.11.4"

services:
- docker

before_script:
- npm install --global elm@^0.18.0

script:
- git clone https://github.com/Ahimta/tweeters-stats-elm.git
- cd tweeters-stats-elm
- elm-package install --yes
- elm-make Main.elm --output=../index.html
- cd ../
- rm -rf tweeters-stats-elm
- docker build --file Dockerfile --tag tweeters-stats-golang .
- docker run -it --rm tweeters-stats-golang ./test