sudo: required

env:
- CONSUMER_KEY=consumerKey CONSUMER_SECRET=consumerSecret CALLBACK_URL=http://localhost:8080/oauth/twitter/callback PORT=8080 HOMEPAGE=/ HOST=localhost:8080 PROTOCOL=http

services:
- docker

script:
- docker build --file Dockerfile.test --tag tweeters-stats-golang-test .
- docker run -it --rm --env NEW_RELIC_LICENSE_KEY= tweeters-stats-golang-test

after_success:
- git clone https://github.com/Ahimta/tweeters-stats-elm.git
- cd tweeters-stats-elm
- elm-package install --yes
- elm-make Main.elm --output=../index.html
- cd ../
- rm -rf tweeters-stats-elm
- pip install awscli --upgrade --user
- aws ecr get-login --no-include-email --region eu-west-1 | bash
- docker build --file Dockerfile.prod --tag tweeters-stats-golang-prod .
- docker tag tweeters-stats-golang-prod:latest $DOCKER_REPO_URL:latest &>/dev/null
- docker push $DOCKER_REPO_URL:latest &>/dev/null
- aws ecs update-service --cluster backend --service backend --force-new-deployment &>/dev/null