sudo: required
language: node_js
node_js:
- "8.11.4"

env:
- CONSUMER_KEY=consumerKey CONSUMER_SECRET=consumerSecret CALLBACK_URL=http://localhost:8080/oauth/twitter/callback PORT=8080 HOMEPAGE=/ HOST=localhost:8080 PROTOCOL=http

services:
- docker

before_script:
- npm install --global elm

script:
- git clone https://github.com/Ahimta/tweeters-stats-elm.git
- cd tweeters-stats-elm
- elm-package install --yes
- elm-make Main.elm --output=../index.html
- cd ../
- rm -rf tweeters-stats-elm
- docker build --file Dockerfile.test --tag tweeters-stats-golang-test .
- docker run -it --rm --env NEW_RELIC_LICENSE_KEY= tweeters-stats-golang-test