sudo: required

env:
- CONSUMER_KEY=consumerKey
- CONSUMER_SECRET=consumerSecret
- CALLBACK_URL=http://localhost:8080/oauth/twitter/callback
- PORT=8080
- HOMEPAGE=/

services:
- docker

script:
- docker build --tag tweeters-stats-golang --build-arg livereload=disabled .
- docker run -it --rm -p 8080:8080 -v $PWD:/go/src/github.com/Ahimta/tweeters-stats-golang tweeters-stats-golang ./test