FROM golang:1.9.2
LABEL Author="Abdullah Alansari <ahimta@gmail.com>"
LABEL Name="tweeters-stats-golang"

RUN go get -u github.com/golang/dep/cmd/dep && \
  go get -u github.com/golang/lint/golint

COPY Gopkg.lock Gopkg.toml /go/src/github.com/Ahimta/tweeters-stats-golang/
WORKDIR /go/src/github.com/Ahimta/tweeters-stats-golang

COPY . /go/src/github.com/Ahimta/tweeters-stats-golang
RUN dep ensure

CMD ./test