FROM golang:1.9.2
LABEL Author="Abdullah Alansari <ahimta@gmail.com>"
LABEL Name="tweeters-stats-golang"

COPY . /go/src/github.com/Ahimta/tweeters-stats-golang
WORKDIR /go/src/github.com/Ahimta/tweeters-stats-golang

RUN go get -u github.com/golang/dep/cmd/dep && \
  go get github.com/newrelic/go-agent && \
  go get -u github.com/golang/lint/golint

RUN dep ensure
CMD ./test