FROM golang:1.10.3
LABEL Author="Abdullah Alansari <ahimta@gmail.com>"
LABEL Name="tweeters-stats-golang"

RUN go get -u github.com/golang/dep/cmd/dep && \
  go get github.com/pilu/fresh

COPY Gopkg.lock Gopkg.toml /go/src/github.com/Ahimta/tweeters-stats-golang/
WORKDIR /go/src/github.com/Ahimta/tweeters-stats-golang

COPY . /go/src/github.com/Ahimta/tweeters-stats-golang
RUN dep ensure

EXPOSE 8080
CMD fresh